<?php

namespace Database\Seeders;

use App\Models\Users;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Users::create([
            'id_user' => 1,
            'password' => Hash::make('admin'),
            'email' => "admin@mail.com",
            'name' => "Mateo",
            'lastname' => "Maturano",
            'telephone' => "155550010",
            'quote' => "Soy el Administrador de Houser",
            'birthday' => "1990-06-01",
            'address' => "Cabildo 2500",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "carpi1.jpg",
            'avatar' => "yo.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 1
        ]);
        Users::create([
            'id_user' => 2,
            'password' => Hash::make('user'),
            'email' => "user@mail.com",
            'name' => "Carolina",
            'lastname' => "Gomez",
            'telephone' => "155550011",
            'quote' => "Soy un Usuario de prueba",
            'birthday' => "1990-05-28",
            'address' => "conde 729",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Colegiales',
            'cp' => 1427,
            'portrait' => "cold1.jpg",
            'avatar' => "perfil1.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 2
        ]);
        Users::create([
            'id_user' => 3,
            'password' => Hash::make('user'),
            'email' => "professional@mail.com",
            'name' => "Javier",
            'lastname' => "Profesional",
            'telephone' => "155550012",
            'quote' => "Soy Técnico de PC",
            'birthday' => "1988-10-15",
            'address' => "Blanco encalada 3000",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "compu1.jpg",
            'avatar' => "javier.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 2,
            'total_rating' => 3.7
        ]);
        Users::create([
            'id_user' => 4,
            'password' => Hash::make('user'),
            'email' => "laurareggiano@mimail.com",
            'name' => "Laura",
            'lastname' => "Reggiano",
            'telephone' => "155550012",
            'quote' => "Soy Ténica de Pc",
            'birthday' => "1988-10-15",
            'address' => "Freire 2400",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "compu2.jpg",
            'avatar' => "laura.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 2,
            'total_rating' => 4.7
        ]);
        Users::create([
            'id_user' => 5,
            'password' => Hash::make('user'),
            'email' => "jorgelaurenzo12@mimail.com",
            'name' => "Jorge",
            'lastname' => "Laurenzo",
            'telephone' => "155550012",
            'quote' => "Soy Carpintero",
            'birthday' => "1988-10-15",
            'address' => "Freire 2500",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "carpi1.jpg",
            'avatar' => "jorge.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 1,
            'total_rating' => 2.9
        ]);
        Users::create([
            'id_user' => 6,
            'password' => Hash::make('user'),
            'email' => "raulrak@mimail.com",
            'name' => "Raul",
            'lastname' => "Rakora",
            'telephone' => "155550012",
            'quote' => "Soy Carpintero y Ebanista",
            'birthday' => "1988-10-15",
            'address' => "Monroe 2100",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "carpi2.jpg",
            'avatar' => "raul.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 1,
            'total_rating' => 5
        ]);
        Users::create([
            'id_user' => 7,
            'password' => Hash::make('user'),
            'email' => "matiburzaco@mimail.com",
            'name' => "Matias",
            'lastname' => "Buzcaco",
            'telephone' => "155550012",
            'quote' => "Soy Pintor de casas y establecimientos",
            'birthday' => "1988-10-15",
            'address' => "Olazabal 1100",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "pintu1.jpg",
            'avatar' => "matias.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 3,
            'total_rating' => 4.1
        ]);
        Users::create([
            'id_user' => 8,
            'password' => Hash::make('user'),
            'email' => "pablojulens@minimail.com",
            'name' => "Pablo",
            'lastname' => "Julens",
            'telephone' => "155550010",
            'quote' => "Soy Pintor hace 10 años",
            'birthday' => "1988-10-15",
            'address' => "Conde 600",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Colegiales',
            'cp' => 1427,
            'portrait' => "pintu2.jpg",
            'avatar' => "pablo.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 3,
            'total_rating' => 0
        ]);
        Users::create([
            'id_user' => 9,
            'password' => Hash::make('user'),
            'email' => "valeriaandreeti@gmail.com",
            'name' => "Valeria",
            'lastname' => "Andreeti",
            'telephone' => "155550010",
            'quote' => "Soy Carpintera profesional hace más de 2 años",
            'birthday' => "1988-10-15",
            'address' => "Cespedes 3000",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Colegiales',
            'cp' => 1427,
            'portrait' => "carpi3.jpg",
            'avatar' => "valeria.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 1,
            'total_rating' => 2.5
        ]);
        Users::create([
            'id_user' => 10,
            'password' => Hash::make('user'),
            'email' => "gladysenglish@gmail.com",
            'name' => "Gladys",
            'lastname' => "Lamanuch",
            'telephone' => "155550010",
            'quote' => "Experta en carpientería de mesitas ratonas y estantes",
            'birthday' => "1988-10-15",
            'address' => "Cramer 828",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Colegiales',
            'cp' => 1427,
            'portrait' => "carpi4.jpg",
            'avatar' => "gladys.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 1,
            'total_rating' => 4
        ]);
        Users::create([
            'id_user' => 11,
            'password' => Hash::make('user'),
            'email' => "teresa@gmail.com",
            'name' => "Teresa",
            'lastname' => "Salendis",
            'telephone' => "155550010",
            'quote' => "He reparado diversos electrodomésticos a lo largo de 15 años",
            'birthday' => "1988-10-15",
            'address' => "Cabildo 3000",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "cold1.jpg",
            'avatar' => "teresa.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 4,
            'total_rating' => 5
        ]);
        Users::create([
            'id_user' => 12,
            'password' => Hash::make('user'),
            'email' => "fedelew@gmail.com",
            'name' => "Federico",
            'lastname' => "Lewis",
            'telephone' => "155550010",
            'quote' => "¡Reparador especial de Aires Acondicionados!",
            'birthday' => "1988-10-15",
            'address' => "Ciudad de la paz 428",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Colegiales',
            'cp' => 1427,
            'portrait' => "cold2.jpg",
            'avatar' => "fede.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 4,
            'total_rating' => 4.6
        ]);
        Users::create([
            'id_user' => 13,
            'password' => Hash::make('user'),
            'email' => "manunande@gmail.com",
            'name' => "Manuel",
            'lastname' => "Nandez",
            'telephone' => "155550010",
            'quote' => "Reparo todo tipo de electrodomésticos: Aires - Heladeras - Hornos y mas!",
            'birthday' => "1988-10-15",
            'address' => "Vidal 2487",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "cold3.jpg",
            'avatar' => "manuel.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 4,
            'total_rating' => 3.8
        ]);
        Users::create([
            'id_user' => 14,
            'password' => Hash::make('user'),
            'email' => "ramirogus@gmail.com",
            'name' => "Ramiro",
            'lastname' => "Gustamonte",
            'telephone' => "155550010",
            'quote' => "Servicio de fletería a domicilio, el mejor servicio en Houser",
            'birthday' => "1988-10-15",
            'address' => "Freire 2300",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "flete1.jpg",
            'avatar' => "ramiro.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 5,
            'total_rating' => 4.5
        ]);
        Users::create([
            'id_user' => 15,
            'password' => Hash::make('user'),
            'email' => "nicolastofe@gmail.com",
            'name' => "Nicolas",
            'lastname' => "Tofe",
            'telephone' => "155550010",
            'quote' => "Servicio de Flete con experiencia de más de 20 años",
            'birthday' => "1988-10-15",
            'address' => "Superí 428",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "flete2.jpg",
            'avatar' => "nicolas.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 5,
            'total_rating' => 4
        ]);
        Users::create([
            'id_user' => 16,
            'password' => Hash::make('user'),
            'email' => "alefernandez@yahoo.com",
            'name' => "Alejandro",
            'lastname' => "Fernandez",
            'telephone' => "1520745026",
            'quote' => "Electricista especializado en hogares y grandes edificaciones.",
            'birthday' => "1972-06-04",
            'address' => "Amenabar 1350",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Belgrano',
            'cp' => 1428,
            'portrait' => "electricista1.jpg",
            'avatar' => "alejandro.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 6,
            'total_rating' => 4.8
        ]);
        Users::create([
            'id_user' => 17,
            'password' => Hash::make('user'),
            'email' => "roberloire@outlook.com",
            'name' => "Roberto",
            'lastname' => "Loire",
            'telephone' => "1534341796",
            'quote' => "Soy electricista matriculado, hago desde reparaciones hasta instalaciones de luz",
            'birthday' => "1970-12-28",
            'address' => "Tucumán 2015",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Balvanera',
            'cp' => 1050,
            'portrait' => "electricista2.jpg",
            'avatar' => "roberto.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 6,
            'total_rating' => 3.9
        ]);
        Users::create([
            'id_user' => 18,
            'password' => Hash::make('user'),
            'email' => "hectoragudo75@gmail.com",
            'name' => "Hector",
            'lastname' => "Agudo",
            'telephone' => "1560823714",
            'quote' => "Técnico electricista matriculado, trabajo en CABA y todo GBA",
            'birthday' => "1975-07-05",
            'address' => "Zuviría 422",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Caballito',
            'cp' => 1424,
            'portrait' => "electricista3.jpg",
            'avatar' => "hector.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 6,
            'total_rating' => 5
        ]);
        Users::create([
            'id_user' => 19,
            'password' => Hash::make('user'),
            'email' => "arancioj@gmail.com",
            'name' => "Julio",
            'lastname' => "Arancio",
            'telephone' => "1560823714",
            'quote' => "Plomero especializado en destapaciones y colocaciones de cañerias",
            'birthday' => "1968-04-22",
            'address' => "Tinogasta 3174",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => 'Villa Del Parque',
            'cp' => 1417,
            'portrait' => "plomero1.jpg",
            'avatar' => "julio.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 7,
            'total_rating' => 4.2
        ]);
        Users::create([
            'id_user' => 20,
            'password' => Hash::make('user'),
            'email' => "fgonzalez@gmail.com",
            'name' => "Federico Javier",
            'lastname' => "Gonzalez",
            'telephone' => "1520406649",
            'quote' => "El plomero más recomendable de Parque Patricios",
            'birthday' => "1968-01-13",
            'address' => "Avenida Brasil 2800",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => "Parque Patricios",
            'cp' => 1260,
            'portrait' => "plomero2.jpg",
            'avatar' => "federicoj.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 7,
            'total_rating' => 3.6
        ]);
        Users::create([
            'id_user' => 21,
            'password' => Hash::make('user'),
            'email' => "alfonsofio@gmail.com",
            'name' => "Alfonso",
            'lastname' => "Fiorente",
            'telephone' => "1570115320",
            'quote' => "Gasista matriculado, reparo calderas de casas y edificios también",
            'birthday' => "1960-02-28",
            'address' => "Junín 1030",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => "Barrio Norte",
            'cp' => 1113,
            'portrait' => "gasista1.jpg",
            'avatar' => "alfonso.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 8,
            'total_rating' => 4.5
        ]);
        Users::create([
            'id_user' => 22,
            'password' => Hash::make('user'),
            'email' => "willylombardo@gmail.com",
            'name' => "Willy",
            'lastname' => "Lombardo",
            'telephone' => "1550761910",
            'quote' => "Soy gasista apto todo tipo de trabajo e instalación, CABA y GBA",
            'birthday' => "1980-09-15",
            'address' => "Jerónimo Salguero 949",
            'state' => "Ciudad Autónoma de Buenos Aires",
            'suburb' => "Almagro",
            'cp' => 1179,
            'portrait' => "gasista2.jpg",
            'avatar' => "willylomb.jpg",
            'alt' => "foto de perfil del usuario",
            'fk_level' => 3,
            'fk_service' => 8,
            'total_rating' => 3.2
        ]);
    }
}

